In [1]:
import pandas as pd
print(dir(pd))

['ArrowDtype', 'BooleanDtype', 'Categorical', 'CategoricalDtype', 'CategoricalIndex', 'DataFrame', 'DateOffset', 'DatetimeIndex', 'DatetimeTZDtype', 'ExcelFile', 'ExcelWriter', 'Flags', 'Float32Dtype', 'Float64Dtype', 'Grouper', 'HDFStore', 'Index', 'IndexSlice', 'Int16Dtype', 'Int32Dtype', 'Int64Dtype', 'Int8Dtype', 'Interval', 'IntervalDtype', 'IntervalIndex', 'MultiIndex', 'NA', 'NaT', 'NamedAgg', 'Period', 'PeriodDtype', 'PeriodIndex', 'RangeIndex', 'Series', 'SparseDtype', 'StringDtype', 'Timedelta', 'TimedeltaIndex', 'Timestamp', 'UInt16Dtype', 'UInt32Dtype', 'UInt64Dtype', 'UInt8Dtype', '__all__', '__builtins__', '__cached__', '__doc__', '__docformat__', '__file__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_built_with_meson', '_config', '_is_numpy_dev', '_libs', '_pandas_datetime_CAPI', '_pandas_parser_CAPI', '_testing', '_typing', '_version_meson', 'annotations', 'api', 'array', 'arrays', 'bdate_range', 'compat', 'concat', 'core', 'crosstab', 'cut', 'date_range', 'describe_option', 'errors', 'eval', 'factorize', 'from_dummies', 'get_dummies', 'get_option', 'infer_freq', 'interval_range', 'io', 'isna', 'isnull', 'json_normalize', 'lreshape', 'melt', 'merge', 'merge_asof', 'merge_ordered', 'notna', 'notnull', 'offsets', 'option_context', 'options', 'pandas', 'period_range', 'pivot', 'pivot_table', 'plotting', 'qcut', 'read_clipboard', 'read_csv', 'read_excel', 'read_feather', 'read_fwf', 'read_gbq', 'read_hdf', 'read_html', 'read_json', 'read_orc', 'read_parquet', 'read_pickle', 'read_sas', 'read_spss', 'read_sql', 'read_sql_query', 'read_sql_table', 'read_stata', 'read_table', 'read_xml', 'reset_option', 'set_eng_float_format', 'set_option', 'show_versions', 'test', 'testing', 'timedelta_range', 'to_datetime', 'to_numeric', 'to_pickle', 'to_timedelta', 'tseries', 'unique', 'util', 'value_counts', 'wide_to_long']

In [3]:
l=list(range(1,11,1))
S1=pd.Series(l)
S1

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

In [4]:
a=list(range(1,11,1))
S2=pd.Series(l,a)

In [5]:
S2

1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
dtype: int64

In [6]:
#indexing on series 

print(S2.iloc[0:5])

1    1
2    2
3    3
4    4
5    5
dtype: int64

In [7]:
S1.iloc[0:10:1]

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

In [8]:
S2.loc[0:10:1]

1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
dtype: int64

In [9]:
S1.iloc[1:10:2]

1     2
3     4
5     6
7     8
9    10
dtype: int64

In [10]:
S1.loc[1,10,2]

IndexingError: Too many indexers

In [11]:
#this error can be asked in inteview quaestion 

#in udi loc will not take integer indexes

In [12]:
house=pd.read_csv('House_Prices.csv')

In [13]:
house

     Home   Price  SqFt  Bedrooms  Bathrooms  Offers Brick Neighborhood
0       1  114300  1790         2          2       2    No         East
1       2  114200  2030         4          2       3    No         East
2       3  114800  1740         3          2       1    No         East
3       4   94700  1980         3          2       3    No         East
4       5  119800  2130         3          3       3    No         East
..    ...     ...   ...       ...        ...     ...   ...          ...
123   124  119700  1900         3          3       3   Yes         East
124   125  147900  2160         4          3       3   Yes         East
125   126  113500  2070         2          2       2    No        North
126   127  149900  2020         3          3       1    No         West
127   128  124600  2250         3          3       4    No        North

[128 rows x 8 columns]

In [14]:
#extract first 20 rows of data and first five columb 

house=house.iloc[0:21,0:5]
house

    Home   Price  SqFt  Bedrooms  Bathrooms
0      1  114300  1790         2          2
1      2  114200  2030         4          2
2      3  114800  1740         3          2
3      4   94700  1980         3          2
4      5  119800  2130         3          3
5      6  114600  1780         3          2
6      7  151600  1830         3          3
7      8  150700  2160         4          2
8      9  119200  2110         4          2
9     10  104000  1730         3          3
10    11  132500  2030         3          2
11    12  123000  1870         2          2
12    13  102600  1910         3          2
13    14  126300  2150         3          3
14    15  176800  2590         4          3
15    16  145800  1780         4          2
16    17  147100  2190         3          3
17    18   83600  1990         3          3
18    19  111400  1700         2          2
19    20  167200  1920         3          3
20    21  116200  1790         3          2

In [15]:
house=house.loc[0:20,['Home','Price','SqFt','Bedrooms']]
house

    Home   Price  SqFt  Bedrooms
0      1  114300  1790         2
1      2  114200  2030         4
2      3  114800  1740         3
3      4   94700  1980         3
4      5  119800  2130         3
5      6  114600  1780         3
6      7  151600  1830         3
7      8  150700  2160         4
8      9  119200  2110         4
9     10  104000  1730         3
10    11  132500  2030         3
11    12  123000  1870         2
12    13  102600  1910         3
13    14  126300  2150         3
14    15  176800  2590         4
15    16  145800  1780         4
16    17  147100  2190         3
17    18   83600  1990         3
18    19  111400  1700         2
19    20  167200  1920         3
20    21  116200  1790         3

In [16]:
d2=pd.read_excel('Copy of UPDATED LED DISBURSEMENT REQUEST (002).xlsx')
d2

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,"LED DISBURSEMENT REQUEST AS AT JUNE 6, 2023",NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,GROUP,PROJECT,AMOUNT (N'B),AMOUNT ($'M),GUARANTEEING BANK,STATUS
6,NaN,NaN,NaN,NaN,1.0,AGRO PROCESSING,QUANTUM PAPER,13.8,NaN,FIDELITY AND UNION BANKS,TREASURY
7,NaN,NaN,NaN,NaN,2.0,CREATIVE AND DIGITAL INDUSTRY,GENESIS DELUXE CINIMAS LTD,1,NaN,FCMB,AVAILMENT IN CIRCULATION
8,NaN,NaN,NaN,NaN,3.0,ENGINEERING AND TECHNOLOGY,CIG MOTORS CO. LTD,6.65,NaN,UNION,TO BE AVAILED
9,NaN,NaN,NaN,NaN,4.0,FOOD AND BEVERAGES,FLOUR MILLS OF NIGERIA PLC,8.22,NaN,"FCMB, GLOBUS AND FBN QUEST",TREASURY
10,NaN,NaN,NaN,NaN,NaN,NaN,ARTEE INDUSTRIES LIMITED,4.18,NaN,FCMB,TREASURY
11,NaN,NaN,NaN,NaN,NaN,NaN,AGRO AND TECHNICAL PROCESSING LTD,5.9,NaN,FCMB,TREASURY
12,NaN,NaN,NaN,NaN,5.0,HOSPITALITY AND TOURISM,OXBOW PROPERTY INVESTMENT LTD,3,NaN,POLARIS BANK,TREASURY
13,NaN,NaN,NaN,NaN,6.0,GENDER BUSINESS,COMPAGNIE INDUSTRIELLE ET COMMERCIALE (CIC) LI...,5,NaN,UNION BANK,TO BE AVAILED
14,NaN,NaN,NaN,NaN,7.0,MINING AND METALS,LAGOSTAR WIRE AND CABLE COMPANY LIMITED,2,NaN,FIDELITY BANK PLC,TREASURY
15,NaN,NaN,NaN,NaN,8.0,MINING AND METALS,COLEMAN TECHNICAL INDUSTRIES LIMITED,10,NaN,INFRACREDIT,TREASURY
16,NaN,NaN,NaN,NaN,9.0,INFRASTRUCTURE AND INTERVENTION,VICTORIA ISLAN POWER,14.2,NaN,INFRACREDIT AND FBN QUEST,AVAILMENT IN CIRCULATION
17,NaN,NaN,NaN,NaN,10.0,OIL AND GAS,CARACAL OIL AND GAS LTD,NaN,6,PROVISDOS BANK,TREASURY
18,NaN,NaN,NaN,NaN,NaN,NaN,ERASKON NIGERIA LTD,4.1,NaN,SUNTRUST AND NCDMB,AVAILMENT IN CIRCULATION
19,NaN,NaN,NaN,NaN,NaN,NaN,FALCON NIGERIA LTD,3,NaN,INFRACREDIT,AVAILMENT IN CIRCULATION
20,NaN,NaN,NaN,NaN,NaN,NaN,TOTAL,81.05,6,NaN,NaN

In [17]:
d3 = d2.iloc[5: ,4: ]
d3
#we used this to remove extra gap

,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
5,NaN,GROUP,PROJECT,AMOUNT (N'B),AMOUNT ($'M),GUARANTEEING BANK,STATUS
6,1.0,AGRO PROCESSING,QUANTUM PAPER,13.8,NaN,FIDELITY AND UNION BANKS,TREASURY
7,2.0,CREATIVE AND DIGITAL INDUSTRY,GENESIS DELUXE CINIMAS LTD,1,NaN,FCMB,AVAILMENT IN CIRCULATION
8,3.0,ENGINEERING AND TECHNOLOGY,CIG MOTORS CO. LTD,6.65,NaN,UNION,TO BE AVAILED
9,4.0,FOOD AND BEVERAGES,FLOUR MILLS OF NIGERIA PLC,8.22,NaN,"FCMB, GLOBUS AND FBN QUEST",TREASURY
10,NaN,NaN,ARTEE INDUSTRIES LIMITED,4.18,NaN,FCMB,TREASURY
11,NaN,NaN,AGRO AND TECHNICAL PROCESSING LTD,5.9,NaN,FCMB,TREASURY
12,5.0,HOSPITALITY AND TOURISM,OXBOW PROPERTY INVESTMENT LTD,3,NaN,POLARIS BANK,TREASURY
13,6.0,GENDER BUSINESS,COMPAGNIE INDUSTRIELLE ET COMMERCIALE (CIC) LI...,5,NaN,UNION BANK,TO BE AVAILED
14,7.0,MINING AND METALS,LAGOSTAR WIRE AND CABLE COMPANY LIMITED,2,NaN,FIDELITY BANK PLC,TREASURY
15,8.0,MINING AND METALS,COLEMAN TECHNICAL INDUSTRIES LIMITED,10,NaN,INFRACREDIT,TREASURY
16,9.0,INFRASTRUCTURE AND INTERVENTION,VICTORIA ISLAN POWER,14.2,NaN,INFRACREDIT AND FBN QUEST,AVAILMENT IN CIRCULATION
17,10.0,OIL AND GAS,CARACAL OIL AND GAS LTD,NaN,6,PROVISDOS BANK,TREASURY
18,NaN,NaN,ERASKON NIGERIA LTD,4.1,NaN,SUNTRUST AND NCDMB,AVAILMENT IN CIRCULATION
19,NaN,NaN,FALCON NIGERIA LTD,3,NaN,INFRACREDIT,AVAILMENT IN CIRCULATION
20,NaN,NaN,TOTAL,81.05,6,NaN,NaN

In [18]:
#iskey aur dheknaaa reh gaye do teen of assign and implace

In [24]:
d3.reset_index()
d3

,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
5,NaN,GROUP,PROJECT,AMOUNT (N'B),AMOUNT ($'M),GUARANTEEING BANK,STATUS
6,1.0,AGRO PROCESSING,QUANTUM PAPER,13.8,NaN,FIDELITY AND UNION BANKS,TREASURY
7,2.0,CREATIVE AND DIGITAL INDUSTRY,GENESIS DELUXE CINIMAS LTD,1,NaN,FCMB,AVAILMENT IN CIRCULATION
8,3.0,ENGINEERING AND TECHNOLOGY,CIG MOTORS CO. LTD,6.65,NaN,UNION,TO BE AVAILED
9,4.0,FOOD AND BEVERAGES,FLOUR MILLS OF NIGERIA PLC,8.22,NaN,"FCMB, GLOBUS AND FBN QUEST",TREASURY
10,NaN,NaN,ARTEE INDUSTRIES LIMITED,4.18,NaN,FCMB,TREASURY
11,NaN,NaN,AGRO AND TECHNICAL PROCESSING LTD,5.9,NaN,FCMB,TREASURY
12,5.0,HOSPITALITY AND TOURISM,OXBOW PROPERTY INVESTMENT LTD,3,NaN,POLARIS BANK,TREASURY
13,6.0,GENDER BUSINESS,COMPAGNIE INDUSTRIELLE ET COMMERCIALE (CIC) LI...,5,NaN,UNION BANK,TO BE AVAILED
14,7.0,MINING AND METALS,LAGOSTAR WIRE AND CABLE COMPANY LIMITED,2,NaN,FIDELITY BANK PLC,TREASURY
15,8.0,MINING AND METALS,COLEMAN TECHNICAL INDUSTRIES LIMITED,10,NaN,INFRACREDIT,TREASURY
16,9.0,INFRASTRUCTURE AND INTERVENTION,VICTORIA ISLAN POWER,14.2,NaN,INFRACREDIT AND FBN QUEST,AVAILMENT IN CIRCULATION
17,10.0,OIL AND GAS,CARACAL OIL AND GAS LTD,NaN,6,PROVISDOS BANK,TREASURY
18,NaN,NaN,ERASKON NIGERIA LTD,4.1,NaN,SUNTRUST AND NCDMB,AVAILMENT IN CIRCULATION
19,NaN,NaN,FALCON NIGERIA LTD,3,NaN,INFRACREDIT,AVAILMENT IN CIRCULATION
20,NaN,NaN,TOTAL,81.05,6,NaN,NaN

In [31]:
d3.reset_index(drop=True, inplace=True)

In [32]:
d3

,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,NaN,GROUP,PROJECT,AMOUNT (N'B),AMOUNT ($'M),GUARANTEEING BANK,STATUS
1,1.0,AGRO PROCESSING,QUANTUM PAPER,13.8,NaN,FIDELITY AND UNION BANKS,TREASURY
2,2.0,CREATIVE AND DIGITAL INDUSTRY,GENESIS DELUXE CINIMAS LTD,1,NaN,FCMB,AVAILMENT IN CIRCULATION
3,3.0,ENGINEERING AND TECHNOLOGY,CIG MOTORS CO. LTD,6.65,NaN,UNION,TO BE AVAILED
4,4.0,FOOD AND BEVERAGES,FLOUR MILLS OF NIGERIA PLC,8.22,NaN,"FCMB, GLOBUS AND FBN QUEST",TREASURY
5,NaN,NaN,ARTEE INDUSTRIES LIMITED,4.18,NaN,FCMB,TREASURY
6,NaN,NaN,AGRO AND TECHNICAL PROCESSING LTD,5.9,NaN,FCMB,TREASURY
7,5.0,HOSPITALITY AND TOURISM,OXBOW PROPERTY INVESTMENT LTD,3,NaN,POLARIS BANK,TREASURY
8,6.0,GENDER BUSINESS,COMPAGNIE INDUSTRIELLE ET COMMERCIALE (CIC) LI...,5,NaN,UNION BANK,TO BE AVAILED
9,7.0,MINING AND METALS,LAGOSTAR WIRE AND CABLE COMPANY LIMITED,2,NaN,FIDELITY BANK PLC,TREASURY
10,8.0,MINING AND METALS,COLEMAN TECHNICAL INDUSTRIES LIMITED,10,NaN,INFRACREDIT,TREASURY
11,9.0,INFRASTRUCTURE AND INTERVENTION,VICTORIA ISLAN POWER,14.2,NaN,INFRACREDIT AND FBN QUEST,AVAILMENT IN CIRCULATION
12,10.0,OIL AND GAS,CARACAL OIL AND GAS LTD,NaN,6,PROVISDOS BANK,TREASURY
13,NaN,NaN,ERASKON NIGERIA LTD,4.1,NaN,SUNTRUST AND NCDMB,AVAILMENT IN CIRCULATION
14,NaN,NaN,FALCON NIGERIA LTD,3,NaN,INFRACREDIT,AVAILMENT IN CIRCULATION
15,NaN,NaN,TOTAL,81.05,6,NaN,NaN

In [33]:
d3 = d3.drop(0)

In [35]:
d3

,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,NaN,GROUP,PROJECT,AMOUNT (N'B),AMOUNT ($'M),GUARANTEEING BANK,STATUS
1,1.0,AGRO PROCESSING,QUANTUM PAPER,13.8,NaN,FIDELITY AND UNION BANKS,TREASURY
2,2.0,CREATIVE AND DIGITAL INDUSTRY,GENESIS DELUXE CINIMAS LTD,1,NaN,FCMB,AVAILMENT IN CIRCULATION
3,3.0,ENGINEERING AND TECHNOLOGY,CIG MOTORS CO. LTD,6.65,NaN,UNION,TO BE AVAILED
4,4.0,FOOD AND BEVERAGES,FLOUR MILLS OF NIGERIA PLC,8.22,NaN,"FCMB, GLOBUS AND FBN QUEST",TREASURY
5,NaN,NaN,ARTEE INDUSTRIES LIMITED,4.18,NaN,FCMB,TREASURY
6,NaN,NaN,AGRO AND TECHNICAL PROCESSING LTD,5.9,NaN,FCMB,TREASURY
7,5.0,HOSPITALITY AND TOURISM,OXBOW PROPERTY INVESTMENT LTD,3,NaN,POLARIS BANK,TREASURY
8,6.0,GENDER BUSINESS,COMPAGNIE INDUSTRIELLE ET COMMERCIALE (CIC) LI...,5,NaN,UNION BANK,TO BE AVAILED
9,7.0,MINING AND METALS,LAGOSTAR WIRE AND CABLE COMPANY LIMITED,2,NaN,FIDELITY BANK PLC,TREASURY
10,8.0,MINING AND METALS,COLEMAN TECHNICAL INDUSTRIES LIMITED,10,NaN,INFRACREDIT,TREASURY
11,9.0,INFRASTRUCTURE AND INTERVENTION,VICTORIA ISLAN POWER,14.2,NaN,INFRACREDIT AND FBN QUEST,AVAILMENT IN CIRCULATION
12,10.0,OIL AND GAS,CARACAL OIL AND GAS LTD,NaN,6,PROVISDOS BANK,TREASURY
13,NaN,NaN,ERASKON NIGERIA LTD,4.1,NaN,SUNTRUST AND NCDMB,AVAILMENT IN CIRCULATION
14,NaN,NaN,FALCON NIGERIA LTD,3,NaN,INFRACREDIT,AVAILMENT IN CIRCULATION
15,NaN,NaN,TOTAL,81.05,6,NaN,NaN